export const insightRouteMap: Record<string, string> = {
  overdue_invoices: "/accounting/invoices?filter=overdue",
  large_invoices: "/accounting/invoices?filter=sent",
  zero_stock: "/inventory/stock?filter=zero_stock",
  low_stock: "/inventory/stock?filter=low_stock",
  draft_journals: "/accounting/journal?filter=draft",
  payroll_anomaly: "/hr/payroll",
  excessive_overtime: "/hr/overtime",
  leave_balance_warning: "/hr/annual-leave",
  stale_leads: "/crm/leads?filter=new",
  high_value_at_risk: "/crm/opportunities?filter=at_risk",
  budget_variance: "/analytics/budget",
  revenue_declining: "/analytics",
  slow_moving: "/analytics/inventory-health",
  reorder_suggestion: "/purchasing/orders",
  expense_spike: "/accounting/expenses",
  duplicate_invoices: "/purchasing/supplier-invoices",
  weekend_postings: "/accounting/journal",
  dormant_accounts: "/crm/companies",
  at_risk_accounts: "/crm/companies",
  // Round 1: 8 new insight types
  pos_high_refund_rate: "/pos",
  pos_not_fiscalized: "/pos/transactions",
  overdue_production: "/inventory/production",
  bom_material_shortage: "/inventory/production",
  unreconciled_statements: "/accounting/bank-statements",
  po_delivery_overdue: "/purchasing/orders",
  quote_aging: "/sales/quotes",
  open_fiscal_periods: "/accounting/fiscal-years",
  // Round 4: cross-module duplicate detection
  cross_module_duplicate: "/purchasing/supplier-invoices",
};
