import React from "react";
import { Route } from "react-router-dom";
import { ProtectedRoute } from "@/components/ProtectedRoute";
import { PageErrorBoundary } from "@/components/shared/PageErrorBoundary";

const AccountingHub = React.lazy(() => import("@/pages/tenant/AccountingHub"));
const ChartOfAccounts = React.lazy(() => import("@/pages/tenant/ChartOfAccounts"));
const JournalEntries = React.lazy(() => import("@/pages/tenant/JournalEntries"));
const Invoices = React.lazy(() => import("@/pages/tenant/Invoices"));
const InvoiceForm = React.lazy(() => import("@/pages/tenant/InvoiceForm"));
const FiscalPeriods = React.lazy(() => import("@/pages/tenant/FiscalPeriods"));
const GeneralLedger = React.lazy(() => import("@/pages/tenant/GeneralLedger"));
const Expenses = React.lazy(() => import("@/pages/tenant/Expenses"));
const Reports = React.lazy(() => import("@/pages/tenant/Reports"));
const TrialBalance = React.lazy(() => import("@/pages/tenant/TrialBalance"));
const IncomeStatement = React.lazy(() => import("@/pages/tenant/IncomeStatement"));
const BalanceSheet = React.lazy(() => import("@/pages/tenant/BalanceSheet"));
const BilansUspeha = React.lazy(() => import("@/pages/tenant/BilansUspeha"));
const BilansStanja = React.lazy(() => import("@/pages/tenant/BilansStanja"));
const AopPositions = React.lazy(() => import("@/pages/tenant/AopPositions"));
const BankStatements = React.lazy(() => import("@/pages/tenant/BankStatements"));
const OpenItems = React.lazy(() => import("@/pages/tenant/OpenItems"));
const PdvPeriods = React.lazy(() => import("@/pages/tenant/PdvPeriods"));
const YearEndClosing = React.lazy(() => import("@/pages/tenant/YearEndClosing"));
const FixedAssets = React.lazy(() => import("@/pages/tenant/FixedAssets"));
const AgingReports = React.lazy(() => import("@/pages/tenant/AgingReports"));
const Deferrals = React.lazy(() => import("@/pages/tenant/Deferrals"));
const Loans = React.lazy(() => import("@/pages/tenant/Loans"));
const FxRevaluation = React.lazy(() => import("@/pages/tenant/FxRevaluation"));
const Kompenzacija = React.lazy(() => import("@/pages/tenant/Kompenzacija"));
const RecurringInvoices = React.lazy(() => import("@/pages/tenant/RecurringInvoices"));
const RecurringJournals = React.lazy(() => import("@/pages/tenant/RecurringJournals"));
const IosBalanceConfirmation = React.lazy(() => import("@/pages/tenant/IosBalanceConfirmation"));
const CostCenterPL = React.lazy(() => import("@/pages/tenant/CostCenterPL"));
const CashRegister = React.lazy(() => import("@/pages/tenant/CashRegister"));
const FxCashRegister = React.lazy(() => import("@/pages/tenant/FxCashRegister"));
const IntercompanyTransactions = React.lazy(() => import("@/pages/tenant/IntercompanyTransactions"));
const ConsolidatedStatements = React.lazy(() => import("@/pages/tenant/ConsolidatedStatements"));
const WithholdingTax = React.lazy(() => import("@/pages/tenant/WithholdingTax"));
const CitTaxReturn = React.lazy(() => import("@/pages/tenant/CitTaxReturn"));
const StatistickiAneks = React.lazy(() => import("@/pages/tenant/StatistickiAneks"));
const KpoBook = React.lazy(() => import("@/pages/tenant/KpoBook"));
const MultiPeriodReports = React.lazy(() => import("@/pages/tenant/MultiPeriodReports"));
const TransferPricing = React.lazy(() => import("@/pages/tenant/TransferPricing"));
const ReportSnapshots = React.lazy(() => import("@/pages/tenant/ReportSnapshots"));
const BankAccounts = React.lazy(() => import("@/pages/tenant/BankAccounts"));
const BankDocumentImport = React.lazy(() => import("@/pages/tenant/BankDocumentImport"));
const CreditDebitNotes = React.lazy(() => import("@/pages/tenant/CreditDebitNotes"));
const ProformaInvoices = React.lazy(() => import("@/pages/tenant/ProformaInvoices"));
const InvoiceRegister = React.lazy(() => import("@/pages/tenant/InvoiceRegister"));
const PK1Book = React.lazy(() => import("@/pages/tenant/reports/PK1Book"));
const PPPPO = React.lazy(() => import("@/pages/tenant/reports/PPPPO"));
const OdOForm = React.lazy(() => import("@/pages/tenant/reports/OdOForm"));
const M4Report = React.lazy(() => import("@/pages/tenant/reports/M4Report"));
const ZpppdvForm = React.lazy(() => import("@/pages/tenant/reports/ZpppdvForm"));
const NotesToFinancialStatements = React.lazy(() => import("@/pages/tenant/reports/NotesToFinancialStatements"));
const IFRSIncomeStatement = React.lazy(() => import("@/pages/tenant/reports/IFRSIncomeStatement"));
const IFRSBalanceSheet = React.lazy(() => import("@/pages/tenant/reports/IFRSBalanceSheet"));
const RevenueContracts = React.lazy(() => import("@/pages/tenant/RevenueContracts"));
const RevenueContractForm = React.lazy(() => import("@/pages/tenant/RevenueContractForm"));
const RevenueContractDetail = React.lazy(() => import("@/pages/tenant/RevenueContractDetail"));
const CashFlowStatement = React.lazy(() => import("@/pages/tenant/CashFlowStatement"));
const ComplianceDashboard = React.lazy(() => import("@/pages/tenant/ComplianceDashboard"));
const KepKnjiga = React.lazy(() => import("@/pages/tenant/KepKnjiga"));
const PoreskiBilans = React.lazy(() => import("@/pages/tenant/PoreskiBilans"));

const m = "accounting";
const B = PageErrorBoundary;

export const accountingRoutes = (
  <>
    <Route path="accounting" element={<ProtectedRoute requiredModule={m}><B><AccountingHub /></B></ProtectedRoute>} />
    <Route path="accounting/chart-of-accounts" element={<ProtectedRoute requiredModule={m}><B><ChartOfAccounts /></B></ProtectedRoute>} />
    <Route path="accounting/journal" element={<ProtectedRoute requiredModule={m}><B><JournalEntries /></B></ProtectedRoute>} />
    <Route path="accounting/invoices" element={<ProtectedRoute requiredModule={m}><B><Invoices /></B></ProtectedRoute>} />
    <Route path="accounting/invoices/new" element={<ProtectedRoute requiredModule={m}><B><InvoiceForm /></B></ProtectedRoute>} />
    <Route path="accounting/invoices/:id" element={<ProtectedRoute requiredModule={m}><B><InvoiceForm /></B></ProtectedRoute>} />
    <Route path="accounting/fiscal-periods" element={<ProtectedRoute requiredModule={m}><B><FiscalPeriods /></B></ProtectedRoute>} />
    <Route path="accounting/ledger" element={<ProtectedRoute requiredModule={m}><B><GeneralLedger /></B></ProtectedRoute>} />
    <Route path="accounting/expenses" element={<ProtectedRoute requiredModule={m}><B><Expenses /></B></ProtectedRoute>} />
    <Route path="accounting/reports" element={<ProtectedRoute requiredModule={m}><B><Reports /></B></ProtectedRoute>} />
    <Route path="accounting/reports/trial-balance" element={<ProtectedRoute requiredModule={m}><B><TrialBalance /></B></ProtectedRoute>} />
    <Route path="accounting/reports/income-statement" element={<ProtectedRoute requiredModule={m}><B><IncomeStatement /></B></ProtectedRoute>} />
    <Route path="accounting/reports/balance-sheet" element={<ProtectedRoute requiredModule={m}><B><BalanceSheet /></B></ProtectedRoute>} />
    <Route path="accounting/reports/bilans-uspeha" element={<ProtectedRoute requiredModule={m}><B><BilansUspeha /></B></ProtectedRoute>} />
    <Route path="accounting/reports/bilans-stanja" element={<ProtectedRoute requiredModule={m}><B><BilansStanja /></B></ProtectedRoute>} />
    <Route path="accounting/reports/aop-positions" element={<ProtectedRoute requiredModule={m}><B><AopPositions /></B></ProtectedRoute>} />
    <Route path="accounting/reports/aging" element={<ProtectedRoute requiredModule={m}><B><AgingReports /></B></ProtectedRoute>} />
    <Route path="accounting/reports/cost-center-pl" element={<ProtectedRoute requiredModule={m}><B><CostCenterPL /></B></ProtectedRoute>} />
    <Route path="accounting/reports/consolidated" element={<ProtectedRoute requiredModule={m}><B><ConsolidatedStatements /></B></ProtectedRoute>} />
    <Route path="accounting/bank-statements" element={<ProtectedRoute requiredModule={m}><B><BankStatements /></B></ProtectedRoute>} />
    <Route path="accounting/open-items" element={<ProtectedRoute requiredModule={m}><B><OpenItems /></B></ProtectedRoute>} />
    <Route path="accounting/ios" element={<ProtectedRoute requiredModule={m}><B><IosBalanceConfirmation /></B></ProtectedRoute>} />
    <Route path="accounting/pdv" element={<ProtectedRoute requiredModule={m}><B><PdvPeriods /></B></ProtectedRoute>} />
    <Route path="accounting/withholding-tax" element={<ProtectedRoute requiredModule={m}><B><WithholdingTax /></B></ProtectedRoute>} />
    <Route path="accounting/cit-return" element={<ProtectedRoute requiredModule={m}><B><CitTaxReturn /></B></ProtectedRoute>} />
    <Route path="accounting/year-end" element={<ProtectedRoute requiredModule={m}><B><YearEndClosing /></B></ProtectedRoute>} />
    <Route path="accounting/fixed-assets" element={<ProtectedRoute requiredModule={m}><B><FixedAssets /></B></ProtectedRoute>} />
    <Route path="accounting/deferrals" element={<ProtectedRoute requiredModule={m}><B><Deferrals /></B></ProtectedRoute>} />
    <Route path="accounting/loans" element={<ProtectedRoute requiredModule={m}><B><Loans /></B></ProtectedRoute>} />
    <Route path="accounting/fx-revaluation" element={<ProtectedRoute requiredModule={m}><B><FxRevaluation /></B></ProtectedRoute>} />
    <Route path="accounting/kompenzacija" element={<ProtectedRoute requiredModule={m}><B><Kompenzacija /></B></ProtectedRoute>} />
    <Route path="accounting/intercompany" element={<ProtectedRoute requiredModule={m}><B><IntercompanyTransactions /></B></ProtectedRoute>} />
    <Route path="accounting/cash-register" element={<ProtectedRoute requiredModule={m}><B><CashRegister /></B></ProtectedRoute>} />
    <Route path="accounting/fx-cash-register" element={<ProtectedRoute requiredModule={m}><B><FxCashRegister /></B></ProtectedRoute>} />
    <Route path="accounting/recurring-invoices" element={<ProtectedRoute requiredModule={m}><B><RecurringInvoices /></B></ProtectedRoute>} />
    <Route path="accounting/recurring-journals" element={<ProtectedRoute requiredModule={m}><B><RecurringJournals /></B></ProtectedRoute>} />
    <Route path="accounting/statisticki-aneks" element={<ProtectedRoute requiredModule={m}><B><StatistickiAneks /></B></ProtectedRoute>} />
    <Route path="accounting/kpo-book" element={<ProtectedRoute requiredModule={m}><B><KpoBook /></B></ProtectedRoute>} />
    <Route path="accounting/reports/multi-period" element={<ProtectedRoute requiredModule={m}><B><MultiPeriodReports /></B></ProtectedRoute>} />
    <Route path="accounting/transfer-pricing" element={<ProtectedRoute requiredModule={m}><B><TransferPricing /></B></ProtectedRoute>} />
    <Route path="accounting/report-snapshots" element={<ProtectedRoute requiredModule={m}><B><ReportSnapshots /></B></ProtectedRoute>} />
    <Route path="accounting/bank-accounts" element={<ProtectedRoute requiredModule={m}><B><BankAccounts /></B></ProtectedRoute>} />
    <Route path="accounting/document-import" element={<ProtectedRoute requiredModule={m}><B><BankDocumentImport /></B></ProtectedRoute>} />
    <Route path="accounting/credit-debit-notes" element={<ProtectedRoute requiredModule={m}><B><CreditDebitNotes /></B></ProtectedRoute>} />
    <Route path="accounting/proforma-invoices" element={<ProtectedRoute requiredModule={m}><B><ProformaInvoices /></B></ProtectedRoute>} />
    <Route path="accounting/invoice-register" element={<ProtectedRoute requiredModule={m}><B><InvoiceRegister /></B></ProtectedRoute>} />
    <Route path="accounting/reports/pk1-book" element={<ProtectedRoute requiredModule={m}><B><PK1Book /></B></ProtectedRoute>} />
    <Route path="accounting/reports/ppp-po" element={<ProtectedRoute requiredModule={m}><B><PPPPO /></B></ProtectedRoute>} />
    <Route path="accounting/reports/od-o" element={<ProtectedRoute requiredModule={m}><B><OdOForm /></B></ProtectedRoute>} />
    <Route path="accounting/reports/m4" element={<ProtectedRoute requiredModule={m}><B><M4Report /></B></ProtectedRoute>} />
    <Route path="accounting/reports/zpppdv" element={<ProtectedRoute requiredModule={m}><B><ZpppdvForm /></B></ProtectedRoute>} />
    <Route path="accounting/reports/notes-to-fs" element={<ProtectedRoute requiredModule={m}><B><NotesToFinancialStatements /></B></ProtectedRoute>} />
    <Route path="accounting/reports/ifrs-income-statement" element={<ProtectedRoute requiredModule={m}><B><IFRSIncomeStatement /></B></ProtectedRoute>} />
    <Route path="accounting/reports/ifrs-balance-sheet" element={<ProtectedRoute requiredModule={m}><B><IFRSBalanceSheet /></B></ProtectedRoute>} />
    <Route path="accounting/revenue-contracts" element={<ProtectedRoute requiredModule={m}><B><RevenueContracts /></B></ProtectedRoute>} />
    <Route path="accounting/revenue-contracts/new" element={<ProtectedRoute requiredModule={m}><B><RevenueContractForm /></B></ProtectedRoute>} />
    <Route path="accounting/revenue-contracts/:id" element={<ProtectedRoute requiredModule={m}><B><RevenueContractDetail /></B></ProtectedRoute>} />
    <Route path="accounting/cash-flow-statement" element={<ProtectedRoute requiredModule={m}><B><CashFlowStatement /></B></ProtectedRoute>} />
    <Route path="accounting/compliance" element={<ProtectedRoute requiredModule={m}><B><ComplianceDashboard /></B></ProtectedRoute>} />
    <Route path="accounting/kep" element={<ProtectedRoute requiredModule={m}><B><KepKnjiga /></B></ProtectedRoute>} />
    <Route path="accounting/reports/poreski-bilans" element={<ProtectedRoute requiredModule={m}><B><PoreskiBilans /></B></ProtectedRoute>} />
  </>
);
