import React from "react";
import { Route } from "react-router-dom";
import { ProtectedRoute } from "@/components/ProtectedRoute";
import { PageErrorBoundary } from "@/components/shared/PageErrorBoundary";

const TenantSettings = React.lazy(() => import("@/pages/tenant/Settings"));
const TenantProfile = React.lazy(() => import("@/pages/tenant/TenantProfile"));
const TenantUsers = React.lazy(() => import("@/pages/tenant/Users"));
const AuditLog = React.lazy(() => import("@/pages/tenant/AuditLog"));
const LegalEntities = React.lazy(() => import("@/pages/tenant/LegalEntities"));
const Locations = React.lazy(() => import("@/pages/tenant/Locations"));
const Warehouses = React.lazy(() => import("@/pages/tenant/Warehouses"));
const CostCenters = React.lazy(() => import("@/pages/tenant/CostCenters"));
const BankAccounts = React.lazy(() => import("@/pages/tenant/BankAccounts"));
const TenantIntegrations = React.lazy(() => import("@/pages/tenant/Integrations"));
const PostingRules = React.lazy(() => import("@/pages/tenant/PostingRules"));
const AccountingArchitecture = React.lazy(() => import("@/pages/tenant/AccountingArchitecture"));
const BusinessRules = React.lazy(() => import("@/pages/tenant/BusinessRules"));
const LegacyImport = React.lazy(() => import("@/pages/tenant/LegacyImport"));
const PayrollParameters = React.lazy(() => import("@/pages/tenant/PayrollParameters"));
const AiAuditLog = React.lazy(() => import("@/pages/tenant/AiAuditLog"));
const CompanyCategoriesSettings = React.lazy(() => import("@/pages/tenant/CompanyCategoriesSettings"));
const OpportunityStagesSettings = React.lazy(() => import("@/pages/tenant/OpportunityStagesSettings"));
const DiscountApprovalRules = React.lazy(() => import("@/pages/tenant/DiscountApprovalRules"));
const TaxRates = React.lazy(() => import("@/pages/tenant/TaxRates"));
const ApprovalWorkflows = React.lazy(() => import("@/pages/tenant/ApprovalWorkflows"));
const PendingApprovals = React.lazy(() => import("@/pages/tenant/PendingApprovals"));
const Currencies = React.lazy(() => import("@/pages/tenant/Currencies"));
const EventMonitor = React.lazy(() => import("@/pages/tenant/EventMonitor"));
const DataProtection = React.lazy(() => import("@/pages/tenant/DataProtection"));
const DataRetentionPolicies = React.lazy(() => import("@/pages/tenant/DataRetentionPolicies"));
const SecurityIncidents = React.lazy(() => import("@/pages/tenant/SecurityIncidents"));
const DmsSettings = React.lazy(() => import("@/pages/tenant/DmsSettings"));
const NotificationCategorySettings = React.lazy(() => import("@/pages/tenant/NotificationCategorySettings"));
const IntegrationHealth = React.lazy(() => import("@/pages/tenant/IntegrationHealth"));
const OrgCompanies = React.lazy(() => import("@/pages/tenant/OrgCompanies"));
const RolePermissions = React.lazy(() => import("@/pages/tenant/RolePermissions"));
const NotificationHistory = React.lazy(() => import("@/pages/tenant/NotificationHistory"));
const ModuleSettings = React.lazy(() => import("@/pages/tenant/ModuleSettings"));
const DataBreachIncidents = React.lazy(() => import("@/pages/tenant/DataBreachIncidents"));
const DataExport = React.lazy(() => import("@/pages/tenant/DataExport"));
const SlaManagement = React.lazy(() => import("@/pages/tenant/SlaManagement"));
const IncidentManagement = React.lazy(() => import("@/pages/tenant/IncidentManagement"));

export const settingsRoutes = (
  <>
    <Route path="settings" element={<ProtectedRoute requiredModule="settings"><PageErrorBoundary><TenantSettings /></PageErrorBoundary></ProtectedRoute>} />
    <Route path="settings/tenant-profile" element={<ProtectedRoute requiredModule="settings"><PageErrorBoundary><TenantProfile /></PageErrorBoundary></ProtectedRoute>} />
    <Route path="settings/users" element={<ProtectedRoute requiredModule="settings-users"><PageErrorBoundary><TenantUsers /></PageErrorBoundary></ProtectedRoute>} />
    <Route path="settings/audit-log" element={<ProtectedRoute requiredModule="settings-audit-log"><PageErrorBoundary><AuditLog /></PageErrorBoundary></ProtectedRoute>} />
    <Route path="settings/legal-entities" element={<ProtectedRoute requiredModule="settings"><PageErrorBoundary><LegalEntities /></PageErrorBoundary></ProtectedRoute>} />
    <Route path="settings/locations" element={<ProtectedRoute requiredModule="settings"><PageErrorBoundary><Locations /></PageErrorBoundary></ProtectedRoute>} />
    <Route path="settings/org-companies" element={<ProtectedRoute requiredModule="settings"><PageErrorBoundary><OrgCompanies /></PageErrorBoundary></ProtectedRoute>} />
    <Route path="settings/warehouses" element={<ProtectedRoute requiredModule="settings"><PageErrorBoundary><Warehouses /></PageErrorBoundary></ProtectedRoute>} />
    <Route path="settings/cost-centers" element={<ProtectedRoute requiredModule="settings"><PageErrorBoundary><CostCenters /></PageErrorBoundary></ProtectedRoute>} />
    <Route path="settings/bank-accounts" element={<ProtectedRoute requiredModule="settings"><PageErrorBoundary><BankAccounts /></PageErrorBoundary></ProtectedRoute>} />
    <Route path="settings/integrations" element={<ProtectedRoute requiredModule="settings-integrations"><PageErrorBoundary><TenantIntegrations /></PageErrorBoundary></ProtectedRoute>} />
    <Route path="settings/posting-rules" element={<ProtectedRoute requiredModule="settings-business-rules"><PageErrorBoundary><PostingRules /></PageErrorBoundary></ProtectedRoute>} />
    <Route path="settings/accounting-architecture" element={<ProtectedRoute requiredModule="settings"><PageErrorBoundary><AccountingArchitecture /></PageErrorBoundary></ProtectedRoute>} />
    <Route path="settings/business-rules" element={<ProtectedRoute requiredModule="settings-business-rules"><PageErrorBoundary><BusinessRules /></PageErrorBoundary></ProtectedRoute>} />
    <Route path="settings/legacy-import" element={<ProtectedRoute requiredModule="settings"><PageErrorBoundary><LegacyImport /></PageErrorBoundary></ProtectedRoute>} />
    <Route path="settings/payroll-parameters" element={<ProtectedRoute requiredModule="settings"><PageErrorBoundary><PayrollParameters /></PageErrorBoundary></ProtectedRoute>} />
    <Route path="settings/ai-audit-log" element={<ProtectedRoute requiredModule="settings"><PageErrorBoundary><AiAuditLog /></PageErrorBoundary></ProtectedRoute>} />
    <Route path="settings/partner-categories" element={<ProtectedRoute requiredModule="settings"><PageErrorBoundary><CompanyCategoriesSettings /></PageErrorBoundary></ProtectedRoute>} />
    <Route path="settings/opportunity-stages" element={<ProtectedRoute requiredModule="settings"><PageErrorBoundary><OpportunityStagesSettings /></PageErrorBoundary></ProtectedRoute>} />
    <Route path="settings/discount-rules" element={<ProtectedRoute requiredModule="settings-approvals"><PageErrorBoundary><DiscountApprovalRules /></PageErrorBoundary></ProtectedRoute>} />
    <Route path="settings/tax-rates" element={<ProtectedRoute requiredModule="settings-tax-rates"><PageErrorBoundary><TaxRates /></PageErrorBoundary></ProtectedRoute>} />
    <Route path="settings/approvals" element={<ProtectedRoute requiredModule="settings-approvals"><PageErrorBoundary><ApprovalWorkflows /></PageErrorBoundary></ProtectedRoute>} />
    <Route path="settings/pending-approvals" element={<ProtectedRoute requiredModule="settings-approvals"><PageErrorBoundary><PendingApprovals /></PageErrorBoundary></ProtectedRoute>} />
    <Route path="settings/currencies" element={<ProtectedRoute requiredModule="settings-currencies"><PageErrorBoundary><Currencies /></PageErrorBoundary></ProtectedRoute>} />
    <Route path="settings/events" element={<ProtectedRoute requiredModule="settings-events"><PageErrorBoundary><EventMonitor /></PageErrorBoundary></ProtectedRoute>} />
    <Route path="settings/data-protection" element={<ProtectedRoute requiredModule="settings"><PageErrorBoundary><DataProtection /></PageErrorBoundary></ProtectedRoute>} />
    <Route path="settings/data-retention" element={<ProtectedRoute requiredModule="settings"><PageErrorBoundary><DataRetentionPolicies /></PageErrorBoundary></ProtectedRoute>} />
    <Route path="settings/security-incidents" element={<ProtectedRoute requiredModule="settings"><PageErrorBoundary><SecurityIncidents /></PageErrorBoundary></ProtectedRoute>} />
    <Route path="settings/dms" element={<ProtectedRoute requiredModule="settings"><PageErrorBoundary><DmsSettings /></PageErrorBoundary></ProtectedRoute>} />
    <Route path="settings/notification-categories" element={<ProtectedRoute requiredModule="settings"><PageErrorBoundary><NotificationCategorySettings /></PageErrorBoundary></ProtectedRoute>} />
    <Route path="settings/integration-health" element={<ProtectedRoute requiredModule="settings-integrations"><PageErrorBoundary><IntegrationHealth /></PageErrorBoundary></ProtectedRoute>} />
    <Route path="settings/role-permissions" element={<ProtectedRoute requiredModule="settings-role-permissions"><PageErrorBoundary><RolePermissions /></PageErrorBoundary></ProtectedRoute>} />
    <Route path="settings/notification-history" element={<ProtectedRoute requiredModule="settings"><PageErrorBoundary><NotificationHistory /></PageErrorBoundary></ProtectedRoute>} />
    <Route path="settings/modules" element={<ProtectedRoute requiredModule="settings"><PageErrorBoundary><ModuleSettings /></PageErrorBoundary></ProtectedRoute>} />
    <Route path="settings/data-breach" element={<ProtectedRoute requiredModule="settings"><PageErrorBoundary><DataBreachIncidents /></PageErrorBoundary></ProtectedRoute>} />
    <Route path="settings/data-export" element={<ProtectedRoute requiredModule="settings"><PageErrorBoundary><DataExport /></PageErrorBoundary></ProtectedRoute>} />
    <Route path="settings/sla" element={<ProtectedRoute requiredModule="settings"><PageErrorBoundary><SlaManagement /></PageErrorBoundary></ProtectedRoute>} />
    <Route path="settings/incidents" element={<ProtectedRoute requiredModule="settings"><PageErrorBoundary><IncidentManagement /></PageErrorBoundary></ProtectedRoute>} />
  </>
);
